apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: operations.custom.app.local
spec:
  group: custom.app.local
  version: v1
  scope: Namespaced
  names:
    plural: operations
    singular: operation
    kind: Operation
    shortNames:
     - oper
